# Generated by Django 5.2 for Podoria CRM.

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.CharField(max_length=48)),
                ("name", models.CharField(max_length=180)),
                ("category", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=24)),
                (
                    "minimum_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-is_active", "name", "sku", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("sku"),
                        name="inventory_material_sku_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_quantity__gte", 0)),
                        name="inventory_material_minimum_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("lot_number", models.CharField(max_length=80)),
                ("received_on", models.DateField()),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("initial_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("current_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("purchase_price_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("supplier_name", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="inventory.material",
                    ),
                ),
            ],
            options={
                "ordering": ("expires_on", "received_on", "lot_number", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("lot_number"),
                        models.F("material"),
                        name="inventory_material_lot_identity_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("initial_quantity__gt", 0)),
                        name="inventory_lot_initial_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("current_quantity__gte", 0)),
                        name="inventory_lot_current_quantity_non_negative",
                    ),
                ],
            },
        ),
    ]
