# Generated by Django 5.2.16 on 2026-07-21 18:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_number", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("RECEIPT", "Надходження"), ("MANUAL_WRITEOFF", "Ручне списання")],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("POSTED", "Проведено")],
                        default="POSTED",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(editable=False, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=3, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.materiallot",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventoryoperation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryoperation",
            constraint=models.UniqueConstraint(
                fields=("created_by", "kind", "idempotency_key"),
                name="inventory_operation_actor_kind_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delta", 0), _negated=True),
                name="inventory_movement_quantity_non_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_after__gte", 0)),
                name="inventory_movement_balance_non_negative",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION inventory_reject_operation_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Posted inventory operations are append-only.'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER inventory_operation_append_only
                BEFORE UPDATE OR DELETE ON inventory_inventoryoperation
                FOR EACH ROW EXECUTE FUNCTION inventory_reject_operation_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS inventory_operation_append_only
                    ON inventory_inventoryoperation;
                DROP FUNCTION IF EXISTS inventory_reject_operation_mutation();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION inventory_reject_movement_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Posted stock movements are append-only.'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER inventory_movement_append_only
                BEFORE UPDATE OR DELETE ON inventory_stockmovement
                FOR EACH ROW EXECUTE FUNCTION inventory_reject_movement_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS inventory_movement_append_only
                    ON inventory_stockmovement;
                DROP FUNCTION IF EXISTS inventory_reject_movement_mutation();
            """,
        ),
    ]
