# Generated by Django 5.2.16 on 2026-07-21 18:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryoperation_stockmovement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryoperation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Надходження"),
                    ("MANUAL_WRITEOFF", "Ручне списання"),
                    ("STOCKTAKE_ADJUSTMENT", "Коригування інвентаризації"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Stocktake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_number", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Чернетка"), ("POSTED", "Проведено")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(editable=False, max_length=64)),
                (
                    "post_idempotency_key",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocktake",
                        to="inventory.inventoryoperation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_inventory_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="StocktakeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_sku", models.CharField(editable=False, max_length=48)),
                ("material_name", models.CharField(editable=False, max_length=180)),
                ("material_unit", models.CharField(editable=False, max_length=24)),
                ("lot_number", models.CharField(editable=False, max_length=80)),
                (
                    "system_quantity",
                    models.DecimalField(decimal_places=3, editable=False, max_digits=12),
                ),
                ("actual_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "purchase_price_minor",
                    models.PositiveBigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocktake_lines",
                        to="inventory.materiallot",
                    ),
                ),
                (
                    "stocktake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inventory.stocktake",
                    ),
                ),
            ],
            options={
                "ordering": ("material_name", "material_sku", "lot_number", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="stocktake",
            constraint=models.UniqueConstraint(
                fields=("created_by", "idempotency_key"),
                name="inventory_stocktake_actor_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.UniqueConstraint(
                fields=("stocktake", "lot"), name="inventory_stocktake_lot_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("system_quantity__gte", 0)),
                name="inventory_stocktake_system_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual_quantity__gte", 0)),
                name="inventory_stocktake_actual_non_negative",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION inventory_reject_stocktake_line_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Stocktake count lines are immutable.'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER inventory_stocktake_line_append_only
                BEFORE UPDATE OR DELETE ON inventory_stocktakeline
                FOR EACH ROW EXECUTE FUNCTION inventory_reject_stocktake_line_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS inventory_stocktake_line_append_only
                    ON inventory_stocktakeline;
                DROP FUNCTION IF EXISTS inventory_reject_stocktake_line_mutation();
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION inventory_guard_stocktake_mutation()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_OP = 'DELETE' OR OLD.status = 'POSTED' THEN
                        RAISE EXCEPTION 'Posted stocktakes are append-only.'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;

                    IF NEW.status <> 'POSTED'
                        OR NEW.operation_id IS NULL
                        OR NEW.posted_by_id IS NULL
                        OR NEW.posted_at IS NULL
                        OR NEW.post_idempotency_key = ''
                        OR NEW.public_number IS DISTINCT FROM OLD.public_number
                        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                        OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
                        OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
                        OR NEW.comment IS DISTINCT FROM OLD.comment
                        OR NEW.created_at IS DISTINCT FROM OLD.created_at
                    THEN
                        RAISE EXCEPTION 'A stocktake draft is immutable except for atomic posting.'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER inventory_stocktake_append_only
                BEFORE UPDATE OR DELETE ON inventory_stocktake
                FOR EACH ROW EXECUTE FUNCTION inventory_guard_stocktake_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS inventory_stocktake_append_only
                    ON inventory_stocktake;
                DROP FUNCTION IF EXISTS inventory_guard_stocktake_mutation();
            """,
        ),
    ]
