# Generated by Django 5.2.16 on 2026-07-21 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_inventoryoperation_kind_stocktake_and_more"),
        ("visits", "0004_visit_payment_handoff_requested_visit_total_minor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryoperation",
            name="source_visit",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_operation",
                to="visits.visit",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryoperation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Надходження"),
                    ("VISIT_USAGE", "Використання у прийомі"),
                    ("MANUAL_WRITEOFF", "Ручне списання"),
                    ("STOCKTAKE_ADJUSTMENT", "Коригування інвентаризації"),
                ],
                max_length=32,
            ),
        ),
    ]
