# Generated by Django 5.2.16 on 2026-07-21 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventoryoperation_source_visit_and_more"),
        ("visits", "0004_visit_payment_handoff_requested_visit_total_minor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventoryoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "VISIT_USAGE"), ("source_visit__isnull", False)),
                    models.Q(
                        models.Q(("kind", "VISIT_USAGE"), _negated=True),
                        ("source_visit__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="inventory_operation_visit_source_consistent",
            ),
        ),
    ]
