# Generated by Django 5.2.16 on 2026-08-05 23:31

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def seed_default_loyalty_policy(apps, schema_editor):  # type: ignore[no-untyped-def]
    LoyaltyPolicy = apps.get_model("discounts", "LoyaltyPolicy")
    LoyaltyPolicy.objects.get_or_create(key="default", defaults={"every_n": 5})


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_global_search_indexes"),
        ("visits", "0006_global_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("percent", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("name", ""), _negated=True),
                            ("name", django.db.models.functions.text.Trim("name")),
                        ),
                        name="discounts_name_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gte", 1), ("percent__lte", 99)),
                        name="discounts_percent_between_1_and_99",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="discounts_version_positive",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="discounts_name_ci_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientLoyaltyState",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="loyalty_state",
                        serialize=False,
                        to="patients.patient",
                    ),
                ),
                ("completed_count", models.PositiveBigIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="discounts_loyalty_state_version_positive",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPolicy",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="default",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("every_n", models.PositiveIntegerField(default=5)),
                ("version", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_policies",
                        to="discounts.discount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key", "default")),
                        name="discounts_loyalty_policy_singleton_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("every_n__gt", 0)),
                        name="discounts_loyalty_every_n_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="discounts_loyalty_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_active", False),
                            models.Q(("discount__isnull", False), ("started_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="discounts_active_loyalty_configured",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="VisitLoyaltyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_number", models.PositiveBigIntegerField()),
                ("eligible", models.BooleanField()),
                ("every_n_snapshot", models.PositiveIntegerField()),
                ("discount_name_snapshot", models.CharField(max_length=120)),
                ("discount_percent_snapshot", models.PositiveSmallIntegerField()),
                ("policy_started_at_snapshot", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_events",
                        to="discounts.discount",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_events",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_event",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("patient_id", "sequence_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "sequence_number"),
                        name="discounts_patient_loyalty_sequence_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("every_n_snapshot__gt", 0),
                            ("sequence_number__gt", 0),
                        ),
                        name="discounts_loyalty_event_ordinals_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percent_snapshot__gte", 1),
                            ("discount_percent_snapshot__lte", 99),
                        ),
                        name="discounts_loyalty_event_percent_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_default_loyalty_policy, migrations.RunPython.noop),
    ]
