# Generated by Django 5.2.16 on 2026-07-21 02:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0002_medical_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("callback", "Перетелефонувати"),
                            ("confirm_appointment", "Підтвердити запис"),
                            ("manual_message", "Написати пацієнту вручну"),
                            ("other", "Інша внутрішня справа"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_at", models.DateTimeField()),
                ("comment", models.TextField(blank=True)),
                ("is_important", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("is_completed", "due_at", "-is_important", "id"),
                "indexes": [
                    models.Index(
                        fields=["assignee", "is_completed", "due_at"],
                        name="workitem_owner_state_due_idx",
                    ),
                    models.Index(fields=["is_completed", "due_at"], name="workitem_state_due_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="workitem_title_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "callback"), _negated=True),
                            ("patient__isnull", False),
                            _connector="OR",
                        ),
                        name="workitem_callback_has_patient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("completed_by__isnull", True),
                                ("is_completed", False),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("completed_by__isnull", False),
                                ("is_completed", True),
                            ),
                            _connector="OR",
                        ),
                        name="workitem_completion_consistent",
                    ),
                ],
            },
        ),
    ]
