# Generated by Django 5.2.16 on 2026-07-21 22:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("visits", "0004_visit_payment_handoff_requested_visit_total_minor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Очікує оплати"),
                            ("PAID", "Оплачено"),
                            ("REFUNDED", "Повернено"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
