# Generated by Django 5.2.16 on 2026-07-22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CREATE_LEDGER_APPEND_ONLY_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_reject_cash_ledger_entry_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Cash ledger entries are append-only.'
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_ledger_entry_append_only
BEFORE UPDATE OR DELETE ON billing_cashledgerentry
FOR EACH ROW EXECUTE FUNCTION billing_reject_cash_ledger_entry_mutation();
"""

DROP_LEDGER_APPEND_ONLY_TRIGGER = """
DROP TRIGGER IF EXISTS billing_cash_ledger_entry_append_only
    ON billing_cashledgerentry;
DROP FUNCTION IF EXISTS billing_reject_cash_ledger_entry_mutation();
"""

CREATE_CASH_SHIFT_LIFECYCLE_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_protect_cash_shift_lifecycle()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash shifts cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.public_number IS DISTINCT FROM NEW.public_number
       OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
       OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'Cash shift identity and opening are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Closed cash shifts are immutable and cannot be reopened.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_shift_lifecycle
BEFORE UPDATE OR DELETE ON billing_cashshift
FOR EACH ROW EXECUTE FUNCTION billing_protect_cash_shift_lifecycle();
"""

DROP_CASH_SHIFT_LIFECYCLE_TRIGGER = """
DROP TRIGGER IF EXISTS billing_cash_shift_lifecycle
    ON billing_cashshift;
DROP FUNCTION IF EXISTS billing_protect_cash_shift_lifecycle();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_number",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Відкрита"), ("CLOSED", "Закрита")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "expected_cash_at_close_minor",
                    models.PositiveBigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "actual_cash_at_close_minor",
                    models.PositiveBigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "discrepancy_minor",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("close_comment", models.TextField(blank=True, editable=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-opened_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CashLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_number",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Оплата"),
                            ("REFUND", "Повернення"),
                            ("DEPOSIT", "Внесення"),
                            ("WITHDRAWAL", "Вилучення"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField(editable=False)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Готівка"),
                            ("CARD", "Картка"),
                            ("TRANSFER", "Переказ"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(editable=False, max_length=128)),
                ("payload_hash", models.CharField(editable=False, max_length=64)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="billing.cashshift",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["cash_shift", "-posted_at", "-id"],
                        name="billing_ledger_shift_time_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("employee",),
                name="billing_one_open_cash_shift_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("actual_cash_at_close_minor__isnull", True),
                        ("close_comment", ""),
                        ("closed_at__isnull", True),
                        ("discrepancy_minor__isnull", True),
                        ("expected_cash_at_close_minor__isnull", True),
                        ("status", "OPEN"),
                    )
                    | models.Q(
                        ("actual_cash_at_close_minor__isnull", False),
                        ("closed_at__isnull", False),
                        ("discrepancy_minor__isnull", False),
                        ("expected_cash_at_close_minor__isnull", False),
                        ("status", "CLOSED"),
                    )
                ),
                name="billing_cash_shift_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashledgerentry",
            constraint=models.UniqueConstraint(
                fields=("created_by", "kind", "idempotency_key"),
                name="billing_ledger_actor_kind_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)),
                name="billing_ledger_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashledgerentry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("kind__in", ("PAYMENT", "REFUND")),
                        ("payment_method__in", ["CASH", "CARD", "TRANSFER"]),
                        ("payment_method__isnull", False),
                    )
                    | models.Q(
                        ("kind__in", ("DEPOSIT", "WITHDRAWAL")),
                        ("payment_method", ""),
                    )
                ),
                name="billing_ledger_kind_method_consistent",
            ),
        ),
        migrations.RunSQL(
            CREATE_CASH_SHIFT_LIFECYCLE_TRIGGER,
            DROP_CASH_SHIFT_LIFECYCLE_TRIGGER,
        ),
        migrations.RunSQL(
            CREATE_LEDGER_APPEND_ONLY_TRIGGER,
            DROP_LEDGER_APPEND_ONLY_TRIGGER,
        ),
    ]
