# Generated by Django 5.2.16 on 2026-07-22 01:52

import uuid
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reject_legacy_untyped_ledger_entries(apps: Any, schema_editor: Any) -> None:
    CashLedgerEntry = apps.get_model("billing", "CashLedgerEntry")
    unsupported = CashLedgerEntry.objects.filter(kind__in=("REFUND", "DEPOSIT", "WITHDRAWAL"))
    if unsupported.exists():
        raise RuntimeError(
            "Cannot install TP-703 over legacy untyped REFUND/DEPOSIT/WITHDRAWAL ledger rows."
        )


def reject_reverse_with_tp703_records(apps: Any, schema_editor: Any) -> None:
    Refund = apps.get_model("billing", "Refund")
    CashAdjustment = apps.get_model("billing", "CashAdjustment")
    if Refund.objects.exists() or CashAdjustment.objects.exists():
        raise RuntimeError(
            "Cannot reverse billing.0004 while immutable refund or cash adjustment records exist."
        )


REPLACE_RECEIVABLE_LIFECYCLE_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_guard_receivable_lifecycle()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Receivables cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF (NEW.amount_minor = 0 AND NEW.status = 'PAID')
           OR (NEW.amount_minor > 0 AND NEW.status = 'OPEN') THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'Receivable initial state is inconsistent.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.visit_id IS DISTINCT FROM NEW.visit_id
       OR OLD.amount_minor IS DISTINCT FROM NEW.amount_minor
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'Receivable identity and amount are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'OPEN' AND NEW.status = 'PAID' THEN
        IF OLD.amount_minor = 0
           OR EXISTS (
               SELECT 1
               FROM billing_payment
               WHERE receivable_id = OLD.id
           ) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'A positive receivable requires a payment before settlement.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'PAID' AND NEW.status = 'REFUNDED' THEN
        IF OLD.amount_minor > 0
           AND EXISTS (
               SELECT 1
                 FROM billing_refund AS refund
                 JOIN billing_payment AS payment
                   ON payment.id = refund.original_payment_id
                WHERE payment.receivable_id = OLD.id
           ) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'A paid receivable requires its full typed refund.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RAISE EXCEPTION 'Receivables only transition OPEN to PAID to REFUNDED.'
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;
"""

RESTORE_RECEIVABLE_LIFECYCLE_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_guard_receivable_lifecycle()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Receivables cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF (NEW.amount_minor = 0 AND NEW.status = 'PAID')
           OR (NEW.amount_minor > 0 AND NEW.status = 'OPEN') THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'Receivable initial state is inconsistent.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.visit_id IS DISTINCT FROM NEW.visit_id
       OR OLD.amount_minor IS DISTINCT FROM NEW.amount_minor
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'Receivable identity and amount are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'OPEN' AND NEW.status = 'PAID' THEN
        IF OLD.amount_minor = 0
           OR EXISTS (
               SELECT 1
               FROM billing_payment
               WHERE receivable_id = OLD.id
           ) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'A positive receivable requires a payment before settlement.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RAISE EXCEPTION 'TP-702 receivables only transition from OPEN to PAID.'
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;
"""

REPLACE_LEDGER_INSERT_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
    available_cash bigint;
BEGIN
    SELECT status, employee_id
      INTO shift_status, shift_employee_id
      FROM billing_cashshift
     WHERE id = NEW.cash_shift_id
     FOR UPDATE;

    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF (NEW.kind = 'REFUND' AND NEW.payment_method = 'CASH')
       OR NEW.kind = 'WITHDRAWAL' THEN
        SELECT COALESCE(
                   SUM(
                       CASE
                           WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                               THEN amount_minor
                           WHEN kind = 'REFUND' AND payment_method = 'CASH'
                               THEN -amount_minor
                           WHEN kind = 'DEPOSIT' THEN amount_minor
                           WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                           ELSE 0
                       END
                   ),
                   0
               )
          INTO available_cash
          FROM billing_cashledgerentry
         WHERE cash_shift_id = NEW.cash_shift_id;

        IF available_cash < NEW.amount_minor THEN
            RAISE EXCEPTION 'Outgoing cash exceeds the available shift balance.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'billing_ledger_sufficient_cash';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

RESTORE_LEDGER_INSERT_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
BEGIN
    SELECT status, employee_id
      INTO shift_status, shift_employee_id
      FROM billing_cashshift
     WHERE id = NEW.cash_shift_id
     FOR UPDATE;

    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

CREATE_REFUND_GUARD_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_guard_refund()
RETURNS trigger AS $$
DECLARE
    ledger_kind varchar(16);
    ledger_amount bigint;
    ledger_method varchar(16);
    ledger_actor_id bigint;
    shift_status varchar(16);
    shift_employee_id bigint;
    payment_amount bigint;
    payment_method varchar(16);
    receivable_status varchar(16);
    employee_name varchar(255);
    employee_email varchar(254);
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Refunds are append-only.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT refund_ledger.kind,
           refund_ledger.amount_minor,
           refund_ledger.payment_method,
           refund_ledger.created_by_id,
           shift.status,
           shift.employee_id,
           payment_ledger.amount_minor,
           payment_ledger.payment_method,
           receivable.status,
           COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email
      INTO ledger_kind,
           ledger_amount,
           ledger_method,
           ledger_actor_id,
           shift_status,
           shift_employee_id,
           payment_amount,
           payment_method,
           receivable_status,
           employee_name,
           employee_email
      FROM billing_cashledgerentry AS refund_ledger
      JOIN billing_cashshift AS shift ON shift.id = refund_ledger.cash_shift_id
      JOIN accounts_user AS actor ON actor.id = refund_ledger.created_by_id
      JOIN billing_payment AS payment ON payment.id = NEW.original_payment_id
      JOIN billing_cashledgerentry AS payment_ledger
        ON payment_ledger.id = payment.ledger_entry_id
      JOIN billing_receivable AS receivable ON receivable.id = payment.receivable_id
     WHERE refund_ledger.id = NEW.ledger_entry_id;

    IF NOT FOUND
       OR ledger_kind <> 'REFUND'
       OR ledger_amount <> payment_amount
       OR ledger_method <> payment_method
       OR ledger_amount <= 0
       OR receivable_status <> 'PAID'
       OR shift_status <> 'OPEN'
       OR ledger_actor_id <> shift_employee_id
       OR NEW.reason = ''
       OR NEW.reason <> BTRIM(NEW.reason)
       OR NEW.employee_name_snapshot <> employee_name
       OR NEW.employee_email_snapshot <> employee_email THEN
        RAISE EXCEPTION 'Refund facts do not match the immutable original payment.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_refund_append_only
BEFORE INSERT OR UPDATE OR DELETE ON billing_refund
FOR EACH ROW EXECUTE FUNCTION billing_guard_refund();
"""

DROP_REFUND_GUARD_TRIGGER = """
DROP TRIGGER IF EXISTS billing_refund_append_only ON billing_refund;
DROP FUNCTION IF EXISTS billing_guard_refund();
"""

CREATE_CASH_ADJUSTMENT_GUARD_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_guard_cash_adjustment()
RETURNS trigger AS $$
DECLARE
    ledger_kind varchar(16);
    ledger_method varchar(16);
    ledger_actor_id bigint;
    shift_status varchar(16);
    shift_employee_id bigint;
    employee_name varchar(255);
    employee_email varchar(254);
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash adjustments are append-only.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT ledger.kind,
           ledger.payment_method,
           ledger.created_by_id,
           shift.status,
           shift.employee_id,
           COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email
      INTO ledger_kind,
           ledger_method,
           ledger_actor_id,
           shift_status,
           shift_employee_id,
           employee_name,
           employee_email
      FROM billing_cashledgerentry AS ledger
      JOIN billing_cashshift AS shift ON shift.id = ledger.cash_shift_id
      JOIN accounts_user AS actor ON actor.id = ledger.created_by_id
     WHERE ledger.id = NEW.ledger_entry_id;

    IF NOT FOUND
       OR ledger_kind NOT IN ('DEPOSIT', 'WITHDRAWAL')
       OR ledger_method <> ''
       OR shift_status <> 'OPEN'
       OR ledger_actor_id <> shift_employee_id
       OR NEW.reason = ''
       OR NEW.reason <> BTRIM(NEW.reason)
       OR NEW.comment <> BTRIM(NEW.comment)
       OR NEW.employee_name_snapshot <> employee_name
       OR NEW.employee_email_snapshot <> employee_email THEN
        RAISE EXCEPTION 'Cash adjustment facts do not match the immutable ledger entry.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_adjustment_append_only
BEFORE INSERT OR UPDATE OR DELETE ON billing_cashadjustment
FOR EACH ROW EXECUTE FUNCTION billing_guard_cash_adjustment();
"""

DROP_CASH_ADJUSTMENT_GUARD_TRIGGER = """
DROP TRIGGER IF EXISTS billing_cash_adjustment_append_only
    ON billing_cashadjustment;
DROP FUNCTION IF EXISTS billing_guard_cash_adjustment();
"""

CREATE_TP703_AGGREGATE_TRIGGERS = """
CREATE OR REPLACE FUNCTION billing_validate_refund_aggregate_at_commit()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM billing_refund AS refund
          JOIN billing_payment AS payment
            ON payment.id = refund.original_payment_id
          JOIN billing_receivable AS receivable
            ON receivable.id = payment.receivable_id
         WHERE refund.ledger_entry_id = NEW.id
           AND receivable.status = 'REFUNDED'
    ) THEN
        RAISE EXCEPTION 'REFUND ledger rows require one settled typed refund.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER billing_refund_ledger_typed
AFTER INSERT ON billing_cashledgerentry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
WHEN (NEW.kind = 'REFUND')
EXECUTE FUNCTION billing_validate_refund_aggregate_at_commit();

CREATE OR REPLACE FUNCTION billing_validate_refund_settlement_at_commit()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM billing_refund AS refund
          JOIN billing_payment AS payment
            ON payment.id = refund.original_payment_id
          JOIN billing_receivable AS receivable
            ON receivable.id = payment.receivable_id
          JOIN billing_cashledgerentry AS ledger
            ON ledger.id = refund.ledger_entry_id
         WHERE refund.id = NEW.id
           AND ledger.kind = 'REFUND'
           AND receivable.status = 'REFUNDED'
    ) THEN
        RAISE EXCEPTION 'Typed refunds require a fully refunded receivable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER billing_refund_receivable_settled
AFTER INSERT ON billing_refund
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION billing_validate_refund_settlement_at_commit();

CREATE OR REPLACE FUNCTION billing_validate_cash_adjustment_ledger_at_commit()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM billing_cashadjustment AS adjustment
         WHERE adjustment.ledger_entry_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'Cash movement ledger rows require one typed cash adjustment.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER billing_cash_adjustment_ledger_typed
AFTER INSERT ON billing_cashledgerentry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
WHEN (NEW.kind IN ('DEPOSIT', 'WITHDRAWAL'))
EXECUTE FUNCTION billing_validate_cash_adjustment_ledger_at_commit();

CREATE OR REPLACE FUNCTION billing_validate_cash_adjustment_typed_at_commit()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM billing_cashadjustment AS adjustment
          JOIN billing_cashledgerentry AS ledger
            ON ledger.id = adjustment.ledger_entry_id
         WHERE adjustment.id = NEW.id
           AND ledger.kind IN ('DEPOSIT', 'WITHDRAWAL')
    ) THEN
        RAISE EXCEPTION 'Typed cash adjustments require a matching cash movement ledger row.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER billing_cash_adjustment_typed
AFTER INSERT ON billing_cashadjustment
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION billing_validate_cash_adjustment_typed_at_commit();
"""

DROP_TP703_AGGREGATE_TRIGGERS = """
DROP TRIGGER IF EXISTS billing_refund_ledger_typed ON billing_cashledgerentry;
DROP TRIGGER IF EXISTS billing_refund_receivable_settled ON billing_refund;
DROP TRIGGER IF EXISTS billing_cash_adjustment_ledger_typed
    ON billing_cashledgerentry;
DROP TRIGGER IF EXISTS billing_cash_adjustment_typed ON billing_cashadjustment;
DROP FUNCTION IF EXISTS billing_validate_refund_aggregate_at_commit();
DROP FUNCTION IF EXISTS billing_validate_refund_settlement_at_commit();
DROP FUNCTION IF EXISTS billing_validate_cash_adjustment_ledger_at_commit();
DROP FUNCTION IF EXISTS billing_validate_cash_adjustment_typed_at_commit();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_payment_and_receivable_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            reject_legacy_untyped_ledger_entries,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CashAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(editable=False, max_length=500)),
                ("comment", models.TextField(blank=True, editable=False)),
                ("employee_name_snapshot", models.CharField(editable=False, max_length=255)),
                ("employee_email_snapshot", models.EmailField(editable=False, max_length=254)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(editable=False, max_length=500)),
                ("employee_name_snapshot", models.CharField(editable=False, max_length=255)),
                ("employee_email_snapshot", models.EmailField(editable=False, max_length=254)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.AddConstraint(
            model_name="cashledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ("DEPOSIT", "WITHDRAWAL"))),
                fields=("created_by", "idempotency_key"),
                name="billing_cash_movement_actor_idempotency_unique",
            ),
        ),
        migrations.AddField(
            model_name="cashadjustment",
            name="ledger_entry",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_adjustment_records",
                to="billing.cashledgerentry",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="ledger_entry",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_records",
                to="billing.cashledgerentry",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="original_payment",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_record",
                to="billing.payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashadjustment",
            constraint=models.UniqueConstraint(
                fields=("ledger_entry",), name="billing_cash_adjustment_ledger_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("employee_name_snapshot", ""), _negated=True),
                    models.Q(("employee_email_snapshot", ""), _negated=True),
                ),
                name="billing_cash_adjustment_identity_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                fields=("ledger_entry",), name="billing_refund_ledger_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", ""), _negated=True),
                    models.Q(("employee_name_snapshot", ""), _negated=True),
                    models.Q(("employee_email_snapshot", ""), _negated=True),
                ),
                name="billing_refund_identity_nonempty",
            ),
        ),
        migrations.RunSQL(
            REPLACE_RECEIVABLE_LIFECYCLE_TRIGGER,
            RESTORE_RECEIVABLE_LIFECYCLE_TRIGGER,
        ),
        migrations.RunSQL(
            REPLACE_LEDGER_INSERT_TRIGGER,
            RESTORE_LEDGER_INSERT_TRIGGER,
        ),
        migrations.RunSQL(
            CREATE_REFUND_GUARD_TRIGGER,
            DROP_REFUND_GUARD_TRIGGER,
        ),
        migrations.RunSQL(
            CREATE_CASH_ADJUSTMENT_GUARD_TRIGGER,
            DROP_CASH_ADJUSTMENT_GUARD_TRIGGER,
        ),
        migrations.RunSQL(
            CREATE_TP703_AGGREGATE_TRIGGERS,
            DROP_TP703_AGGREGATE_TRIGGERS,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reject_reverse_with_tp703_records,
        ),
    ]
