# Generated by Django 5.2.16 on 2026-07-22

from typing import Any

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def reject_legacy_closed_shifts(apps: Any, schema_editor: Any) -> None:
    CashShift = apps.get_model("billing", "CashShift")
    if CashShift.objects.filter(status="CLOSED").exists():
        raise RuntimeError(
            "Cannot install TP-704 over legacy CLOSED cash shifts without trustworthy "
            "closer and idempotency metadata. Reconcile those rows before migrating."
        )


def backfill_immutable_actor_snapshots(apps: Any, schema_editor: Any) -> None:
    CashShift = apps.get_model("billing", "CashShift")
    CashLedgerEntry = apps.get_model("billing", "CashLedgerEntry")
    Payment = apps.get_model("billing", "Payment")
    Refund = apps.get_model("billing", "Refund")
    CashAdjustment = apps.get_model("billing", "CashAdjustment")

    for shift in CashShift.objects.select_related("employee").iterator():
        employee = shift.employee
        display_name = f"{employee.first_name} {employee.last_name}".strip() or employee.email
        shift.employee_name_snapshot = display_name
        shift.employee_email_snapshot = employee.email
        shift.employee_role_snapshot = employee.role
        shift.save(
            update_fields=(
                "employee_name_snapshot",
                "employee_email_snapshot",
                "employee_role_snapshot",
            )
        )

    typed_actor_labels: dict[Any, tuple[str, str]] = {}
    for model in (Payment, Refund, CashAdjustment):
        for ledger_id, name, email in model.objects.values_list(
            "ledger_entry_id",
            "employee_name_snapshot",
            "employee_email_snapshot",
        ).iterator():
            typed_actor_labels[ledger_id] = (name, email)

    for entry in CashLedgerEntry.objects.select_related("created_by").iterator():
        actor = entry.created_by
        current_name = f"{actor.first_name} {actor.last_name}".strip() or actor.email
        snapshot_name, snapshot_email = typed_actor_labels.get(
            entry.pk,
            (current_name, actor.email),
        )
        entry.actor_name_snapshot = snapshot_name
        entry.actor_email_snapshot = snapshot_email
        entry.actor_role_snapshot = actor.role
        entry.save(
            update_fields=(
                "actor_name_snapshot",
                "actor_email_snapshot",
                "actor_role_snapshot",
            )
        )


def reject_reverse_with_closed_shifts(apps: Any, schema_editor: Any) -> None:
    CashShift = apps.get_model("billing", "CashShift")
    if CashShift.objects.filter(status="CLOSED").exists():
        raise RuntimeError(
            "Cannot reverse billing.0005 while CLOSED cash shifts depend on immutable "
            "TP-704 reconciliation, closer, and idempotency metadata."
        )


DROP_LEDGER_APPEND_ONLY_TRIGGER_ONLY = """
DROP TRIGGER IF EXISTS billing_cash_ledger_entry_append_only
    ON billing_cashledgerentry;
"""


CREATE_LEDGER_APPEND_ONLY_TRIGGER_ONLY = """
CREATE TRIGGER billing_cash_ledger_entry_append_only
BEFORE UPDATE OR DELETE ON billing_cashledgerentry
FOR EACH ROW EXECUTE FUNCTION billing_reject_cash_ledger_entry_mutation();
"""


REPLACE_CASH_SHIFT_LIFECYCLE_TRIGGER = """
DROP TRIGGER IF EXISTS billing_cash_shift_lifecycle ON billing_cashshift;

CREATE OR REPLACE FUNCTION billing_protect_cash_shift_lifecycle()
RETURNS trigger AS $$
DECLARE
    expected_cash numeric;
    employee_name varchar(255);
    employee_email varchar(254);
    employee_role varchar(20);
    closer_name varchar(255);
    closer_email varchar(254);
    closer_role varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash shifts cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        SELECT COALESCE(
                   NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
                   actor.email
               ),
               actor.email,
               actor.role
          INTO employee_name, employee_email, employee_role
          FROM accounts_user AS actor
         WHERE actor.id = NEW.employee_id;

        IF NOT FOUND
           OR NEW.employee_name_snapshot IS DISTINCT FROM employee_name
           OR NEW.employee_email_snapshot IS DISTINCT FROM employee_email
           OR NEW.employee_role_snapshot IS DISTINCT FROM employee_role THEN
            RAISE EXCEPTION 'Cash shift opener snapshots must match the opening employee.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'Cash shifts must be inserted in the OPEN state.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.public_number IS DISTINCT FROM NEW.public_number
       OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
       OR OLD.employee_name_snapshot IS DISTINCT FROM NEW.employee_name_snapshot
       OR OLD.employee_email_snapshot IS DISTINCT FROM NEW.employee_email_snapshot
       OR OLD.employee_role_snapshot IS DISTINCT FROM NEW.employee_role_snapshot
       OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'Cash shift identity, opener snapshots, and opening are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Closed cash shifts are immutable and cannot be reopened.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status <> 'OPEN' OR NEW.status <> 'CLOSED' THEN
        RAISE EXCEPTION 'An open cash shift can only transition to closed.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT COALESCE(
               SUM(
                   CASE
                       WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                           THEN amount_minor
                       WHEN kind = 'REFUND' AND payment_method = 'CASH'
                           THEN -amount_minor
                       WHEN kind = 'DEPOSIT' THEN amount_minor
                       WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                       ELSE 0
                   END
               ),
               0
           )
      INTO expected_cash
      FROM billing_cashledgerentry
     WHERE cash_shift_id = OLD.id;

    IF NEW.expected_cash_at_close_minor IS DISTINCT FROM expected_cash THEN
        RAISE EXCEPTION 'Cash-shift expected cash must equal the ledger-derived balance.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.actual_cash_at_close_minor IS NULL
       OR NEW.discrepancy_minor IS DISTINCT FROM (
           NEW.actual_cash_at_close_minor - NEW.expected_cash_at_close_minor
       ) THEN
        RAISE EXCEPTION 'Cash-shift discrepancy must equal actual minus expected cash.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_comment IS DISTINCT FROM BTRIM(NEW.close_comment)
       OR (NEW.discrepancy_minor <> 0 AND BTRIM(NEW.close_comment) = '') THEN
        RAISE EXCEPTION 'A non-zero cash discrepancy requires a trimmed comment.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_idempotency_key IS DISTINCT FROM BTRIM(NEW.close_idempotency_key)
       OR BTRIM(NEW.close_idempotency_key) = ''
       OR NEW.close_payload_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Cash-shift close idempotency metadata is invalid.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email,
           actor.role
      INTO closer_name, closer_email, closer_role
      FROM accounts_user AS actor
     WHERE actor.id = NEW.closed_by_id;

    IF NOT FOUND
       OR NEW.closed_by_name_snapshot IS DISTINCT FROM closer_name
       OR NEW.closed_by_email_snapshot IS DISTINCT FROM closer_email
       OR NEW.closed_by_role_snapshot IS DISTINCT FROM closer_role THEN
        RAISE EXCEPTION 'Cash shift closer snapshots must match the closing actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_shift_lifecycle
BEFORE INSERT OR UPDATE OR DELETE ON billing_cashshift
FOR EACH ROW EXECUTE FUNCTION billing_protect_cash_shift_lifecycle();
"""


RESTORE_CASH_SHIFT_LIFECYCLE_TRIGGER = """
DROP TRIGGER IF EXISTS billing_cash_shift_lifecycle ON billing_cashshift;

CREATE OR REPLACE FUNCTION billing_protect_cash_shift_lifecycle()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash shifts cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.public_number IS DISTINCT FROM NEW.public_number
       OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
       OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'Cash shift identity and opening are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Closed cash shifts are immutable and cannot be reopened.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_shift_lifecycle
BEFORE UPDATE OR DELETE ON billing_cashshift
FOR EACH ROW EXECUTE FUNCTION billing_protect_cash_shift_lifecycle();
"""


REPLACE_LEDGER_INSERT_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
    available_cash bigint;
    actor_name varchar(255);
    actor_email varchar(254);
    actor_role varchar(20);
BEGIN
    SELECT status, employee_id
      INTO shift_status, shift_employee_id
      FROM billing_cashshift
     WHERE id = NEW.cash_shift_id
     FOR UPDATE;

    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email,
           actor.role
      INTO actor_name, actor_email, actor_role
      FROM accounts_user AS actor
     WHERE actor.id = NEW.created_by_id;

    IF NOT FOUND
       OR NEW.actor_name_snapshot IS DISTINCT FROM actor_name
       OR NEW.actor_email_snapshot IS DISTINCT FROM actor_email
       OR NEW.actor_role_snapshot IS DISTINCT FROM actor_role THEN
        RAISE EXCEPTION 'Cash ledger actor snapshots must match the posting actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF (NEW.kind = 'REFUND' AND NEW.payment_method = 'CASH')
       OR NEW.kind = 'WITHDRAWAL' THEN
        SELECT COALESCE(
                   SUM(
                       CASE
                           WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                               THEN amount_minor
                           WHEN kind = 'REFUND' AND payment_method = 'CASH'
                               THEN -amount_minor
                           WHEN kind = 'DEPOSIT' THEN amount_minor
                           WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                           ELSE 0
                       END
                   ),
                   0
               )
          INTO available_cash
          FROM billing_cashledgerentry
         WHERE cash_shift_id = NEW.cash_shift_id;

        IF available_cash < NEW.amount_minor THEN
            RAISE EXCEPTION 'Outgoing cash exceeds the available shift balance.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'billing_ledger_sufficient_cash';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


RESTORE_LEDGER_INSERT_TRIGGER = """
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
    available_cash bigint;
BEGIN
    SELECT status, employee_id
      INTO shift_status, shift_employee_id
      FROM billing_cashshift
     WHERE id = NEW.cash_shift_id
     FOR UPDATE;

    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF (NEW.kind = 'REFUND' AND NEW.payment_method = 'CASH')
       OR NEW.kind = 'WITHDRAWAL' THEN
        SELECT COALESCE(
                   SUM(
                       CASE
                           WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                               THEN amount_minor
                           WHEN kind = 'REFUND' AND payment_method = 'CASH'
                               THEN -amount_minor
                           WHEN kind = 'DEPOSIT' THEN amount_minor
                           WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                           ELSE 0
                       END
                   ),
                   0
               )
          INTO available_cash
          FROM billing_cashledgerentry
         WHERE cash_shift_id = NEW.cash_shift_id;

        IF available_cash < NEW.amount_minor THEN
            RAISE EXCEPTION 'Outgoing cash exceeds the available shift balance.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'billing_ledger_sufficient_cash';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_refund_cash_adjustments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            reject_legacy_closed_shifts,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="cashshift",
            name="billing_cash_shift_state_consistent",
        ),
        migrations.AddField(
            model_name="cashledgerentry",
            name="actor_email_snapshot",
            field=models.EmailField(default="", editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name="cashledgerentry",
            name="actor_name_snapshot",
            field=models.CharField(default="", editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="cashledgerentry",
            name="actor_role_snapshot",
            field=models.CharField(default="", editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="close_idempotency_key",
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="close_payload_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_cash_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="closed_by_email_snapshot",
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="closed_by_name_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="closed_by_role_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="employee_email_snapshot",
            field=models.EmailField(default="", editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="employee_name_snapshot",
            field=models.CharField(default="", editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="employee_role_snapshot",
            field=models.CharField(default="", editable=False, max_length=20),
        ),
        migrations.RunSQL(
            DROP_LEDGER_APPEND_ONLY_TRIGGER_ONLY,
            CREATE_LEDGER_APPEND_ONLY_TRIGGER_ONLY,
        ),
        migrations.RunPython(
            backfill_immutable_actor_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            CREATE_LEDGER_APPEND_ONLY_TRIGGER_ONLY,
            DROP_LEDGER_APPEND_ONLY_TRIGGER_ONLY,
        ),
        migrations.AddConstraint(
            model_name="cashledgerentry",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(actor_name_snapshot="")
                    & ~models.Q(actor_email_snapshot="")
                    & ~models.Q(actor_role_snapshot="")
                ),
                name="billing_ledger_actor_snapshot_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="CLOSED"),
                fields=("closed_by", "close_idempotency_key"),
                name="billing_shift_close_actor_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status="OPEN",
                        closed_at__isnull=True,
                        expected_cash_at_close_minor__isnull=True,
                        actual_cash_at_close_minor__isnull=True,
                        discrepancy_minor__isnull=True,
                        close_comment="",
                        closed_by__isnull=True,
                        closed_by_name_snapshot="",
                        closed_by_email_snapshot="",
                        closed_by_role_snapshot="",
                        close_idempotency_key="",
                        close_payload_hash="",
                    )
                    | models.Q(
                        status="CLOSED",
                        closed_at__isnull=False,
                        expected_cash_at_close_minor__isnull=False,
                        actual_cash_at_close_minor__isnull=False,
                        discrepancy_minor__isnull=False,
                        closed_by__isnull=False,
                    )
                    & ~models.Q(closed_by_name_snapshot="")
                    & ~models.Q(closed_by_email_snapshot="")
                    & ~models.Q(closed_by_role_snapshot="")
                    & ~models.Q(close_idempotency_key="")
                    & ~models.Q(close_payload_hash="")
                ),
                name="billing_cash_shift_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(employee_name_snapshot="")
                    & ~models.Q(employee_email_snapshot="")
                    & ~models.Q(employee_role_snapshot="")
                ),
                name="billing_cash_shift_opener_snapshot_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="OPEN")
                    | models.Q(
                        discrepancy_minor=(
                            models.F("actual_cash_at_close_minor")
                            - models.F("expected_cash_at_close_minor")
                        )
                    )
                ),
                name="billing_cash_shift_discrepancy_formula",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="OPEN")
                    | models.Q(discrepancy_minor=0)
                    | ~models.Q(close_comment="")
                ),
                name="billing_cash_shift_discrepancy_comment",
            ),
        ),
        migrations.RunSQL(
            REPLACE_CASH_SHIFT_LIFECYCLE_TRIGGER,
            RESTORE_CASH_SHIFT_LIFECYCLE_TRIGGER,
        ),
        migrations.RunSQL(
            REPLACE_LEDGER_INSERT_TRIGGER,
            RESTORE_LEDGER_INSERT_TRIGGER,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reject_reverse_with_closed_shifts,
        ),
    ]
