# Generated by Django 5.2.16 on 2026-08-06

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def preflight_and_backfill_legacy_cash_shifts(apps: Any, schema_editor: Any) -> None:
    CashDrawer = apps.get_model("billing", "CashDrawer")
    CashShift = apps.get_model("billing", "CashShift")
    connection = schema_editor.connection

    open_count = CashShift.objects.filter(status="OPEN").count()
    if open_count > 1:
        raise RuntimeError(
            "TP-1016 preflight failed: more than one OPEN cash shift exists. "
            "Reconcile the physical drawer manually before retrying the migration."
        )

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
              FROM billing_cashshift AS shift
             WHERE shift.status = 'CLOSED'
               AND (
                    shift.expected_cash_at_close_minor IS NULL
                 OR shift.actual_cash_at_close_minor IS NULL
                 OR shift.discrepancy_minor IS NULL
                 OR shift.discrepancy_minor
                       IS DISTINCT FROM (
                           shift.actual_cash_at_close_minor
                           - shift.expected_cash_at_close_minor
                       )
                 OR shift.expected_cash_at_close_minor IS DISTINCT FROM (
                      SELECT COALESCE(
                                 SUM(
                                     CASE
                                         WHEN ledger.kind = 'PAYMENT'
                                              AND ledger.payment_method = 'CASH'
                                             THEN ledger.amount_minor
                                         WHEN ledger.kind = 'REFUND'
                                              AND ledger.payment_method = 'CASH'
                                             THEN -ledger.amount_minor
                                         WHEN ledger.kind = 'DEPOSIT'
                                             THEN ledger.amount_minor
                                         WHEN ledger.kind = 'WITHDRAWAL'
                                             THEN -ledger.amount_minor
                                         ELSE 0
                                     END
                                 ),
                                 0
                             )
                        FROM billing_cashledgerentry AS ledger
                       WHERE ledger.cash_shift_id = shift.id
                 )
               )
            """
        )
        invalid_closed_count = int(cursor.fetchone()[0])
        if invalid_closed_count:
            raise RuntimeError(
                "TP-1016 preflight failed: CLOSED cash-shift reconciliation is invalid."
            )

        orphan_checks = (
            (
                "cash ledger",
                """
                SELECT COUNT(*)
                  FROM billing_cashledgerentry AS ledger
                  LEFT JOIN billing_cashshift AS shift ON shift.id = ledger.cash_shift_id
                 WHERE shift.id IS NULL
                """,
            ),
            (
                "payment",
                """
                SELECT COUNT(*)
                  FROM billing_payment AS payment
                  LEFT JOIN billing_cashledgerentry AS ledger
                    ON ledger.id = payment.ledger_entry_id
                 WHERE ledger.id IS NULL
                """,
            ),
            (
                "refund",
                """
                SELECT COUNT(*)
                  FROM billing_refund AS refund
                  LEFT JOIN billing_cashledgerentry AS ledger
                    ON ledger.id = refund.ledger_entry_id
                  LEFT JOIN billing_payment AS payment
                    ON payment.id = refund.original_payment_id
                 WHERE ledger.id IS NULL OR payment.id IS NULL
                """,
            ),
            (
                "cash adjustment",
                """
                SELECT COUNT(*)
                  FROM billing_cashadjustment AS adjustment
                  LEFT JOIN billing_cashledgerentry AS ledger
                    ON ledger.id = adjustment.ledger_entry_id
                 WHERE ledger.id IS NULL
                """,
            ),
        )
        for label, query in orphan_checks:
            cursor.execute(query)
            if int(cursor.fetchone()[0]):
                raise RuntimeError(f"TP-1016 preflight failed: orphan {label} rows exist.")

    drawer, _ = CashDrawer.objects.get_or_create(key="main")
    CashShift.objects.filter(drawer__isnull=True).update(
        drawer=drawer,
        opening_cash_minor=0,
        opening_source_shift=None,
        opening_basis="LEGACY",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_global_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashDrawer",
            fields=[
                (
                    "key",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key", "main")),
                        name="billing_cash_drawer_is_main",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="cashshift",
            name="drawer",
            field=models.ForeignKey(
                blank=True,
                db_column="drawer_key",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="billing.cashdrawer",
                to_field="key",
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="opening_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEGACY", "Історична"),
                    ("INITIAL", "Перша зміна"),
                    ("CARRY_FORWARD", "Перенесення залишку"),
                ],
                editable=False,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="opening_cash_minor",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="opening_source_shift",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carried_forward_to_shifts",
                to="billing.cashshift",
            ),
        ),
        migrations.AddIndex(
            model_name="cashshift",
            index=models.Index(
                fields=["drawer", "status", "-closed_at", "-id"],
                name="billing_drawer_state_idx",
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE billing_cashshift DISABLE TRIGGER billing_cash_shift_lifecycle;",
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            preflight_and_backfill_legacy_cash_shifts,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE billing_cashshift ENABLE TRIGGER billing_cash_shift_lifecycle;",
            migrations.RunSQL.noop,
        ),
    ]
