# Generated by Django 5.2.16 on 2026-08-06

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def lock_and_finish_bridge_backfill(apps: Any, schema_editor: Any) -> None:
    CashDrawer = apps.get_model("billing", "CashDrawer")
    CashShift = apps.get_model("billing", "CashShift")
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute(
            "LOCK TABLE billing_cashdrawer, billing_cashshift IN SHARE ROW EXCLUSIVE MODE"
        )

    if CashShift.objects.filter(status="OPEN").count() > 1:
        raise RuntimeError(
            "TP-1016 activation failed: more than one OPEN cash shift exists. "
            "No shift was selected or closed automatically."
        )

    drawer, _ = CashDrawer.objects.get_or_create(key="main")
    incomplete = CashShift.objects.filter(
        models.Q(drawer__isnull=True)
        | models.Q(opening_cash_minor__isnull=True)
        | models.Q(opening_basis__isnull=True)
    )
    incomplete.update(
        drawer=drawer,
        opening_cash_minor=0,
        opening_source_shift=None,
        opening_basis="LEGACY",
    )

    if CashShift.objects.exclude(drawer=drawer).exists():
        raise RuntimeError("TP-1016 activation failed: a non-main cash drawer is referenced.")


def reject_reverse_after_activation(apps: Any, schema_editor: Any) -> None:
    CashShift = apps.get_model("billing", "CashShift")
    if CashShift.objects.exclude(opening_basis="LEGACY").exists():
        raise RuntimeError(
            "Cannot reverse billing.0008 after INITIAL or CARRY_FORWARD cash shifts exist."
        )
    if CashShift.objects.exclude(opening_cash_minor=0).exists():
        raise RuntimeError(
            "Cannot reverse billing.0008 while cash shifts carry an opening balance."
        )
    if CashShift.objects.filter(opening_source_shift__isnull=False).exists():
        raise RuntimeError(
            "Cannot reverse billing.0008 while a carry-forward source is referenced."
        )


REPLACE_CASH_SHIFT_LIFECYCLE_TRIGGER = r"""
DROP TRIGGER IF EXISTS billing_cash_shift_lifecycle ON billing_cashshift;

CREATE OR REPLACE FUNCTION billing_protect_cash_shift_lifecycle()
RETURNS trigger AS $$
DECLARE
    expected_cash numeric;
    employee_name varchar(255);
    employee_email varchar(254);
    employee_role varchar(20);
    closer_name varchar(255);
    closer_email varchar(254);
    closer_role varchar(20);
    latest_closed_id uuid;
    source_actual numeric;
    source_drawer varchar(32);
    source_status varchar(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash shifts cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        PERFORM 1
          FROM billing_cashdrawer
         WHERE key = NEW.drawer_key
         FOR UPDATE;
        IF NOT FOUND OR NEW.drawer_key <> 'main' THEN
            RAISE EXCEPTION 'Cash shifts require the main clinic drawer.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        SELECT COALESCE(
                   NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
                   actor.email
               ),
               actor.email,
               actor.role
          INTO employee_name, employee_email, employee_role
          FROM accounts_user AS actor
         WHERE actor.id = NEW.employee_id;

        IF NOT FOUND
           OR NEW.employee_name_snapshot IS DISTINCT FROM employee_name
           OR NEW.employee_email_snapshot IS DISTINCT FROM employee_email
           OR NEW.employee_role_snapshot IS DISTINCT FROM employee_role THEN
            RAISE EXCEPTION 'Cash shift opener snapshots must match the opening employee.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'Cash shifts must be inserted in the OPEN state.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.opening_basis = 'LEGACY' THEN
            RAISE EXCEPTION 'New LEGACY cash shifts are forbidden after TP-1016 activation.'
                USING ERRCODE = 'integrity_constraint_violation';
        ELSIF NEW.opening_basis = 'INITIAL' THEN
            IF NEW.opening_cash_minor <> 0
               OR NEW.opening_source_shift_id IS NOT NULL
               OR EXISTS (
                   SELECT 1
                     FROM billing_cashshift AS previous
                    WHERE previous.drawer_key = NEW.drawer_key
                      AND previous.status = 'CLOSED'
               ) THEN
                RAISE EXCEPTION 'INITIAL is allowed only before the first closed drawer shift.'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
        ELSIF NEW.opening_basis = 'CARRY_FORWARD' THEN
            SELECT previous.id
              INTO latest_closed_id
              FROM billing_cashshift AS previous
             WHERE previous.drawer_key = NEW.drawer_key
               AND previous.status = 'CLOSED'
             ORDER BY previous.closed_at DESC, previous.id DESC
             LIMIT 1
             FOR UPDATE;

            SELECT source.actual_cash_at_close_minor, source.drawer_key, source.status
              INTO source_actual, source_drawer, source_status
              FROM billing_cashshift AS source
             WHERE source.id = NEW.opening_source_shift_id;

            IF latest_closed_id IS NULL
               OR NEW.opening_source_shift_id IS DISTINCT FROM latest_closed_id
               OR source_drawer IS DISTINCT FROM NEW.drawer_key
               OR source_status IS DISTINCT FROM 'CLOSED'
               OR source_actual IS NULL
               OR NEW.opening_cash_minor IS DISTINCT FROM source_actual THEN
                RAISE EXCEPTION 'Carry-forward must use the latest committed actual cash.'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
        ELSE
            RAISE EXCEPTION 'Cash-shift opening basis is invalid.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.id IS DISTINCT FROM NEW.id
       OR OLD.public_number IS DISTINCT FROM NEW.public_number
       OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
       OR OLD.employee_name_snapshot IS DISTINCT FROM NEW.employee_name_snapshot
       OR OLD.employee_email_snapshot IS DISTINCT FROM NEW.employee_email_snapshot
       OR OLD.employee_role_snapshot IS DISTINCT FROM NEW.employee_role_snapshot
       OR OLD.drawer_key IS DISTINCT FROM NEW.drawer_key
       OR OLD.opening_cash_minor IS DISTINCT FROM NEW.opening_cash_minor
       OR OLD.opening_source_shift_id IS DISTINCT FROM NEW.opening_source_shift_id
       OR OLD.opening_basis IS DISTINCT FROM NEW.opening_basis
       OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'Cash shift identity, opener, drawer, and opening are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Closed cash shifts are immutable and cannot be reopened.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.status <> 'OPEN' OR NEW.status <> 'CLOSED' THEN
        RAISE EXCEPTION 'An open cash shift can only transition to closed.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT NEW.opening_cash_minor + COALESCE(
               SUM(
                   CASE
                       WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                           THEN amount_minor
                       WHEN kind = 'REFUND' AND payment_method = 'CASH'
                           THEN -amount_minor
                       WHEN kind = 'DEPOSIT' THEN amount_minor
                       WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                       ELSE 0
                   END
               ),
               0
           )
      INTO expected_cash
      FROM billing_cashledgerentry
     WHERE cash_shift_id = OLD.id;

    IF NEW.expected_cash_at_close_minor IS DISTINCT FROM expected_cash THEN
        RAISE EXCEPTION 'Cash-shift expected cash must include opening and ledger balance.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.actual_cash_at_close_minor IS NULL
       OR NEW.discrepancy_minor IS DISTINCT FROM (
           NEW.actual_cash_at_close_minor - NEW.expected_cash_at_close_minor
       ) THEN
        RAISE EXCEPTION 'Cash-shift discrepancy must equal actual minus expected cash.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_comment IS DISTINCT FROM BTRIM(NEW.close_comment)
       OR (NEW.discrepancy_minor <> 0 AND BTRIM(NEW.close_comment) = '') THEN
        RAISE EXCEPTION 'A non-zero cash discrepancy requires a trimmed comment.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_idempotency_key IS DISTINCT FROM BTRIM(NEW.close_idempotency_key)
       OR BTRIM(NEW.close_idempotency_key) = ''
       OR NEW.close_payload_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Cash-shift close idempotency metadata is invalid.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email,
           actor.role
      INTO closer_name, closer_email, closer_role
      FROM accounts_user AS actor
     WHERE actor.id = NEW.closed_by_id;

    IF NOT FOUND
       OR NEW.closed_by_name_snapshot IS DISTINCT FROM closer_name
       OR NEW.closed_by_email_snapshot IS DISTINCT FROM closer_email
       OR NEW.closed_by_role_snapshot IS DISTINCT FROM closer_role THEN
        RAISE EXCEPTION 'Cash shift closer snapshots must match the closing actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_shift_lifecycle
BEFORE INSERT OR UPDATE OR DELETE ON billing_cashshift
FOR EACH ROW EXECUTE FUNCTION billing_protect_cash_shift_lifecycle();
"""


REPLACE_LEDGER_INSERT_TRIGGER = r"""
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
    shift_opening_cash bigint;
    available_cash bigint;
    actor_name varchar(255);
    actor_email varchar(254);
    actor_role varchar(20);
BEGIN
    SELECT status, employee_id, opening_cash_minor
      INTO shift_status, shift_employee_id, shift_opening_cash
      FROM billing_cashshift
     WHERE id = NEW.cash_shift_id
     FOR UPDATE;

    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    SELECT COALESCE(
               NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''),
               actor.email
           ),
           actor.email,
           actor.role
      INTO actor_name, actor_email, actor_role
      FROM accounts_user AS actor
     WHERE actor.id = NEW.created_by_id;

    IF NOT FOUND
       OR NEW.actor_name_snapshot IS DISTINCT FROM actor_name
       OR NEW.actor_email_snapshot IS DISTINCT FROM actor_email
       OR NEW.actor_role_snapshot IS DISTINCT FROM actor_role THEN
        RAISE EXCEPTION 'Cash ledger actor snapshots must match the posting actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF (NEW.kind = 'REFUND' AND NEW.payment_method = 'CASH')
       OR NEW.kind = 'WITHDRAWAL' THEN
        SELECT shift_opening_cash + COALESCE(
                   SUM(
                       CASE
                           WHEN kind = 'PAYMENT' AND payment_method = 'CASH'
                               THEN amount_minor
                           WHEN kind = 'REFUND' AND payment_method = 'CASH'
                               THEN -amount_minor
                           WHEN kind = 'DEPOSIT' THEN amount_minor
                           WHEN kind = 'WITHDRAWAL' THEN -amount_minor
                           ELSE 0
                       END
                   ),
                   0
               )
          INTO available_cash
          FROM billing_cashledgerentry
         WHERE cash_shift_id = NEW.cash_shift_id;

        IF available_cash < NEW.amount_minor THEN
            RAISE EXCEPTION 'Outgoing cash exceeds the available drawer balance.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'billing_ledger_sufficient_cash';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


RESTORE_CASH_SHIFT_LIFECYCLE_TRIGGER = r"""
DROP TRIGGER IF EXISTS billing_cash_shift_lifecycle ON billing_cashshift;

CREATE OR REPLACE FUNCTION billing_protect_cash_shift_lifecycle()
RETURNS trigger AS $$
DECLARE
    expected_cash numeric;
    employee_name varchar(255);
    employee_email varchar(254);
    employee_role varchar(20);
    closer_name varchar(255);
    closer_email varchar(254);
    closer_role varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Cash shifts cannot be deleted.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF TG_OP = 'INSERT' THEN
        SELECT COALESCE(NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''), actor.email),
               actor.email, actor.role
          INTO employee_name, employee_email, employee_role
          FROM accounts_user AS actor WHERE actor.id = NEW.employee_id;
        IF NOT FOUND OR NEW.employee_name_snapshot IS DISTINCT FROM employee_name
           OR NEW.employee_email_snapshot IS DISTINCT FROM employee_email
           OR NEW.employee_role_snapshot IS DISTINCT FROM employee_role THEN
            RAISE EXCEPTION 'Cash shift opener snapshots must match the opening employee.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'Cash shifts must be inserted in the OPEN state.'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.id IS DISTINCT FROM NEW.id OR OLD.public_number IS DISTINCT FROM NEW.public_number
       OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
       OR OLD.employee_name_snapshot IS DISTINCT FROM NEW.employee_name_snapshot
       OR OLD.employee_email_snapshot IS DISTINCT FROM NEW.employee_email_snapshot
       OR OLD.employee_role_snapshot IS DISTINCT FROM NEW.employee_role_snapshot
       OR OLD.opened_at IS DISTINCT FROM NEW.opened_at THEN
        RAISE EXCEPTION 'Cash shift identity, opener snapshots, and opening are immutable.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Closed cash shifts are immutable and cannot be reopened.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.status <> 'OPEN' OR NEW.status <> 'CLOSED' THEN
        RAISE EXCEPTION 'An open cash shift can only transition to closed.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    SELECT COALESCE(SUM(CASE WHEN kind = 'PAYMENT' AND payment_method = 'CASH' THEN amount_minor
                            WHEN kind = 'REFUND' AND payment_method = 'CASH' THEN -amount_minor
                            WHEN kind = 'DEPOSIT' THEN amount_minor
                            WHEN kind = 'WITHDRAWAL' THEN -amount_minor ELSE 0 END), 0)
      INTO expected_cash FROM billing_cashledgerentry WHERE cash_shift_id = OLD.id;
    IF NEW.expected_cash_at_close_minor IS DISTINCT FROM expected_cash THEN
        RAISE EXCEPTION 'Cash-shift expected cash must equal the ledger-derived balance.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.actual_cash_at_close_minor IS NULL OR NEW.discrepancy_minor IS DISTINCT FROM
       (NEW.actual_cash_at_close_minor - NEW.expected_cash_at_close_minor) THEN
        RAISE EXCEPTION 'Cash-shift discrepancy must equal actual minus expected cash.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_comment IS DISTINCT FROM BTRIM(NEW.close_comment)
       OR (NEW.discrepancy_minor <> 0 AND BTRIM(NEW.close_comment) = '') THEN
        RAISE EXCEPTION 'A non-zero cash discrepancy requires a trimmed comment.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.close_idempotency_key IS DISTINCT FROM BTRIM(NEW.close_idempotency_key)
       OR BTRIM(NEW.close_idempotency_key) = '' OR NEW.close_payload_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Cash-shift close idempotency metadata is invalid.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    SELECT COALESCE(NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''), actor.email),
           actor.email, actor.role
      INTO closer_name, closer_email, closer_role
      FROM accounts_user AS actor WHERE actor.id = NEW.closed_by_id;
    IF NOT FOUND OR NEW.closed_by_name_snapshot IS DISTINCT FROM closer_name
       OR NEW.closed_by_email_snapshot IS DISTINCT FROM closer_email
       OR NEW.closed_by_role_snapshot IS DISTINCT FROM closer_role THEN
        RAISE EXCEPTION 'Cash shift closer snapshots must match the closing actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER billing_cash_shift_lifecycle
BEFORE INSERT OR UPDATE OR DELETE ON billing_cashshift
FOR EACH ROW EXECUTE FUNCTION billing_protect_cash_shift_lifecycle();
"""


RESTORE_LEDGER_INSERT_TRIGGER = r"""
CREATE OR REPLACE FUNCTION billing_validate_cash_ledger_entry_insert()
RETURNS trigger AS $$
DECLARE
    shift_status varchar(16);
    shift_employee_id bigint;
    available_cash bigint;
    actor_name varchar(255);
    actor_email varchar(254);
    actor_role varchar(20);
BEGIN
    SELECT status, employee_id INTO shift_status, shift_employee_id
      FROM billing_cashshift WHERE id = NEW.cash_shift_id FOR UPDATE;
    IF NOT FOUND OR shift_status <> 'OPEN' THEN
        RAISE EXCEPTION 'Cash ledger entries require an open shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF shift_employee_id <> NEW.created_by_id THEN
        RAISE EXCEPTION 'Cash ledger entry actor must own the shift.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    SELECT COALESCE(NULLIF(BTRIM(CONCAT_WS(' ', actor.first_name, actor.last_name)), ''), actor.email),
           actor.email, actor.role
      INTO actor_name, actor_email, actor_role
      FROM accounts_user AS actor WHERE actor.id = NEW.created_by_id;
    IF NOT FOUND OR NEW.actor_name_snapshot IS DISTINCT FROM actor_name
       OR NEW.actor_email_snapshot IS DISTINCT FROM actor_email
       OR NEW.actor_role_snapshot IS DISTINCT FROM actor_role THEN
        RAISE EXCEPTION 'Cash ledger actor snapshots must match the posting actor.'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF (NEW.kind = 'REFUND' AND NEW.payment_method = 'CASH') OR NEW.kind = 'WITHDRAWAL' THEN
        SELECT COALESCE(SUM(CASE WHEN kind = 'PAYMENT' AND payment_method = 'CASH' THEN amount_minor
                                WHEN kind = 'REFUND' AND payment_method = 'CASH' THEN -amount_minor
                                WHEN kind = 'DEPOSIT' THEN amount_minor
                                WHEN kind = 'WITHDRAWAL' THEN -amount_minor ELSE 0 END), 0)
          INTO available_cash FROM billing_cashledgerentry WHERE cash_shift_id = NEW.cash_shift_id;
        IF available_cash < NEW.amount_minor THEN
            RAISE EXCEPTION 'Outgoing cash exceeds the available shift balance.'
                USING ERRCODE = '23514', CONSTRAINT = 'billing_ledger_sufficient_cash';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_cash_drawer_expand"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE billing_cashshift DISABLE TRIGGER billing_cash_shift_lifecycle;",
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            lock_and_finish_bridge_backfill,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE billing_cashshift ENABLE TRIGGER billing_cash_shift_lifecycle;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="drawer",
            field=models.ForeignKey(
                db_column="drawer_key",
                default="main",
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="billing.cashdrawer",
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="opening_basis",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Історична"),
                    ("INITIAL", "Перша зміна"),
                    ("CARRY_FORWARD", "Перенесення залишку"),
                ],
                default="INITIAL",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="opening_cash_minor",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("drawer",),
                name="billing_one_open_cash_shift_per_drawer",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="cashshift",
            name="billing_one_open_cash_shift_per_employee",
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("opening_source_shift__isnull", False)),
                fields=("opening_source_shift",),
                name="billing_cash_shift_source_used_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        opening_basis="LEGACY",
                        opening_cash_minor=0,
                        opening_source_shift__isnull=True,
                    )
                    | models.Q(
                        opening_basis="INITIAL",
                        opening_cash_minor=0,
                        opening_source_shift__isnull=True,
                    )
                    | models.Q(
                        opening_basis="CARRY_FORWARD",
                        opening_source_shift__isnull=False,
                    )
                ),
                name="billing_cash_shift_opening_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(opening_source_shift__isnull=True)
                    | ~models.Q(opening_source_shift=models.F("id"))
                ),
                name="billing_cash_shift_source_not_self",
            ),
        ),
        migrations.RunSQL(
            REPLACE_CASH_SHIFT_LIFECYCLE_TRIGGER,
            RESTORE_CASH_SHIFT_LIFECYCLE_TRIGGER,
        ),
        migrations.RunSQL(
            REPLACE_LEDGER_INSERT_TRIGGER,
            RESTORE_LEDGER_INSERT_TRIGGER,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reject_reverse_after_activation,
        ),
    ]
