# Generated by Django 5.2.16 on 2026-07-21

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_existing_profiles(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Patient = apps.get_model("patients", "Patient")
    PatientMedicalProfile = apps.get_model("patients", "PatientMedicalProfile")
    PatientMedicalProfile.objects.bulk_create(
        [
            PatientMedicalProfile(patient_id=patient_id)
            for patient_id in Patient.objects.values_list("pk", flat=True)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedicalProfile",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="medical_profile",
                        serialize=False,
                        to="patients.patient",
                    ),
                ),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("chronic_conditions", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
