# Generated by Django 5.2.16 on 2026-07-21 19:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0002_medical_profile"),
        ("scheduling", "0002_appointment_cancellation_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_number", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Чернетка"), ("COMPLETED", "Завершено")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("complaints", models.TextField(blank=True, max_length=4000)),
                ("has_no_complaints", models.BooleanField(default=False)),
                ("objective_examination", models.TextField(blank=True, max_length=10000)),
                ("detected_conditions", models.JSONField(blank=True, default=list)),
                ("podologist_notes", models.TextField(blank=True, max_length=10000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["specialist", "status"], name="visits_specialist_status_idx"
                    ),
                    models.Index(
                        fields=["patient", "started_at"], name="visits_patient_started_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("has_no_complaints", True), ("complaints", "")),
                            models.Q(
                                ("has_no_complaints", False),
                                models.Q(("complaints", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="visits_complaints_xor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)), name="visits_version_positive"
                    ),
                ],
            },
        ),
    ]
