# Generated by Django 5.2.16 on 2026-07-21 20:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0003_status_schedule"),
        ("inventory", "0003_alter_inventoryoperation_kind_stocktake_and_more"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitMaterialLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_sku", models.CharField(editable=False, max_length=48)),
                ("material_name", models.CharField(editable=False, max_length=180)),
                ("material_unit", models.CharField(editable=False, max_length=24)),
                ("lot_number", models.CharField(editable=False, max_length=80)),
                ("expires_on", models.DateField(blank=True, editable=False, null=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_draft_lines",
                        to="inventory.materiallot",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_draft_lines",
                        to="inventory.material",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_lines",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("material_name", "material_sku", "lot_number", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visit", "lot"), name="visits_material_lot_line_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="visits_material_quantity_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitServiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_code", models.CharField(editable=False, max_length=32)),
                ("service_name", models.CharField(editable=False, max_length=160)),
                ("duration_minutes", models.PositiveSmallIntegerField(editable=False)),
                ("price_minor", models.PositiveBigIntegerField(editable=False)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_draft_lines",
                        to="clinic.service",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_lines",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "service_name", "service_code", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visit", "service"), name="visits_service_line_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("visit",),
                        name="visits_one_primary_service",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="visits_service_quantity_positive",
                    ),
                ],
            },
        ),
    ]
