# Generated by Django 5.2.16 on 2026-07-21 21:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0002_visitmaterialline_visitserviceline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("BEFORE", "До процедури"), ("AFTER", "Після процедури")],
                        max_length=8,
                    ),
                ),
                ("object_key", models.CharField(editable=False, max_length=255, unique=True)),
                ("content_type", models.CharField(editable=False, max_length=32)),
                ("size", models.PositiveIntegerField(editable=False)),
                ("width", models.PositiveIntegerField(editable=False)),
                ("height", models.PositiveIntegerField(editable=False)),
                ("original_name", models.CharField(editable=False, max_length=255)),
                (
                    "preview_object_key",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "preview_content_type",
                    models.CharField(blank=True, editable=False, max_length=32),
                ),
                (
                    "preview_status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Обробляється"),
                            ("READY", "Готове"),
                            ("FAILED", "Помилка"),
                        ],
                        default="PROCESSING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_visit_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="visits.visit",
                    ),
                ),
            ],
            options={"ordering": ("kind", "created_at", "id")},
        ),
        migrations.CreateModel(
            name="VisitPhotoUploadIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("BEFORE", "До процедури"), ("AFTER", "Після процедури")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Очікує файл"), ("FINALIZED", "Завершено")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_photo_upload_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_photo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_intent",
                        to="visits.visitphoto",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_upload_intents",
                        to="visits.visit",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="visitphoto",
            index=models.Index(
                fields=["visit", "kind", "created_at"],
                name="visits_photo_kind_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gt", 0)),
                name="visits_photo_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gt", 0)),
                name="visits_photo_width_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gt", 0)),
                name="visits_photo_height_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="visitphotouploadintent",
            index=models.Index(
                fields=["status", "expires_at"],
                name="visits_photo_intent_exp_idx",
            ),
        ),
    ]
