# Generated by Django 5.2.16 on 2026-07-21 22:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0003_visitphoto_visitphotouploadintent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="payment_handoff_requested",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="total_minor",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="VisitFinishResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(editable=False, max_length=64)),
                ("result", models.JSONField(default=dict, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finish_result",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visit", "idempotency_key"), name="visits_finish_visit_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(max_length=10000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("text", ""), _negated=True),
                        name="visits_recommendation_text_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="visits_recommendation_version_positive",
                    ),
                ],
            },
        ),
    ]
