# Generated by Django 5.2.16 on 2026-07-21 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_medical_profile"),
        ("scheduling", "0002_appointment_cancellation_reason"),
        ("visits", "0004_visit_payment_handoff_requested_visit_total_minor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "status", "-completed_at", "-id"],
                name="visits_patient_history_idx",
            ),
        ),
    ]
