# Generated by Django 5.2.16 on 2026-07-21 00:11

import uuid
from datetime import time

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

STATUS_CONFIGS = (
    ("NEW", "Новий", "#64748B", True, True, False),
    ("PENDING_CONFIRMATION", "Очікує підтвердження", "#F59E0B", True, True, False),
    ("CONFIRMED", "Підтверджено", "#2563EB", True, True, False),
    ("ARRIVED", "Пацієнт прийшов", "#7C3AED", True, True, True),
    ("IN_PROGRESS", "Прийом триває", "#0F766E", True, False, True),
    ("COMPLETED", "Завершено", "#16A34A", True, False, True),
    ("CANCELED", "Скасовано", "#DC2626", True, True, False),
    ("NO_SHOW", "Неявка", "#475569", True, True, False),
)


def seed_statuses_and_schedule(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    AppointmentStatusConfig = apps.get_model("clinic", "AppointmentStatusConfig")
    ClinicWorkday = apps.get_model("clinic", "ClinicWorkday")
    ClinicBreak = apps.get_model("clinic", "ClinicBreak")
    for code, label, color, manual_admin, manual_reception, manual_podologist in STATUS_CONFIGS:
        AppointmentStatusConfig.objects.get_or_create(
            code=code,
            defaults={
                "label": label,
                "color": color,
                "manual_admin": manual_admin,
                "manual_reception": manual_reception,
                "manual_podologist": manual_podologist,
            },
        )
    for weekday in range(7):
        workday, created = ClinicWorkday.objects.get_or_create(
            weekday=weekday,
            defaults={
                "is_working": weekday < 5,
                "start_time": time(9, 0) if weekday < 5 else None,
                "end_time": time(18, 0) if weekday < 5 else None,
            },
        )
        if created and weekday < 5:
            ClinicBreak.objects.create(
                workday=workday,
                start_time=time(13, 0),
                end_time=time(14, 0),
            )


CREATE_STATUS_PROTECTION_TRIGGER = """
CREATE OR REPLACE FUNCTION clinic_protect_system_status()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'system status configurations cannot be deleted';
    END IF;
    IF NEW.code <> OLD.code THEN
        RAISE EXCEPTION 'system status codes are immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER clinic_system_status_protected
BEFORE UPDATE OR DELETE ON clinic_appointmentstatusconfig
FOR EACH ROW EXECUTE FUNCTION clinic_protect_system_status();
"""

DROP_STATUS_PROTECTION_TRIGGER = """
DROP TRIGGER IF EXISTS clinic_system_status_protected ON clinic_appointmentstatusconfig;
DROP FUNCTION IF EXISTS clinic_protect_system_status();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentStatusConfig",
            fields=[
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("color", models.CharField(max_length=7)),
                ("manual_admin", models.BooleanField(default=True)),
                ("manual_reception", models.BooleanField(default=False)),
                ("manual_podologist", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ClinicWorkday",
            fields=[
                ("weekday", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("is_working", models.BooleanField(default=False)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("weekday",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="clinic_workday_weekday_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", True),
                                ("is_working", False),
                                ("start_time__isnull", True),
                            ),
                            models.Q(
                                ("end_time__isnull", False),
                                ("is_working", True),
                                ("start_time__isnull", False),
                                ("start_time__lt", models.F("end_time")),
                            ),
                            _connector="OR",
                        ),
                        name="clinic_workday_valid_hours",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "workday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="clinic.clinicworkday",
                    ),
                ),
            ],
            options={
                "ordering": ("start_time", "end_time", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="clinic_break_valid_range",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_statuses_and_schedule, migrations.RunPython.noop),
        migrations.RunSQL(CREATE_STATUS_PROTECTION_TRIGGER, DROP_STATUS_PROTECTION_TRIGGER),
    ]
