from django.urls import path

from apps.inventory.views import (
    InventoryOperationDetailView,
    ManualWriteoffCreateView,
    MaterialDetailView,
    MaterialListCreateView,
    MaterialLotListView,
    MovementExportView,
    MovementListView,
    ReceiptCreateView,
    StocktakeDetailView,
    StocktakeListCreateView,
    StocktakePostView,
    StocktakePreviewView,
    SupplierDetailView,
    SupplierListCreateView,
)

urlpatterns = [
    path("inventory/materials", MaterialListCreateView.as_view(), name="inventory-material-list"),
    path(
        "inventory/materials/<uuid:material_id>",
        MaterialDetailView.as_view(),
        name="inventory-material-detail",
    ),
    path(
        "inventory/materials/<uuid:material_id>/lots",
        MaterialLotListView.as_view(),
        name="inventory-material-lot-list",
    ),
    path(
        "inventory/suppliers",
        SupplierListCreateView.as_view(),
        name="inventory-supplier-list",
    ),
    path(
        "inventory/suppliers/<uuid:supplier_id>",
        SupplierDetailView.as_view(),
        name="inventory-supplier-detail",
    ),
    path("inventory/receipts", ReceiptCreateView.as_view(), name="inventory-receipt-create"),
    path(
        "inventory/write-offs",
        ManualWriteoffCreateView.as_view(),
        name="inventory-manual-writeoff-create",
    ),
    path(
        "inventory/stocktakes/preview",
        StocktakePreviewView.as_view(),
        name="inventory-stocktake-preview",
    ),
    path(
        "inventory/stocktakes",
        StocktakeListCreateView.as_view(),
        name="inventory-stocktake-create",
    ),
    path(
        "inventory/stocktakes/<uuid:stocktake_id>",
        StocktakeDetailView.as_view(),
        name="inventory-stocktake-detail",
    ),
    path(
        "inventory/stocktakes/<uuid:stocktake_id>/post",
        StocktakePostView.as_view(),
        name="inventory-stocktake-post",
    ),
    path(
        "inventory/movements/export",
        MovementExportView.as_view(),
        name="inventory-movement-export",
    ),
    path(
        "inventory/movements",
        MovementListView.as_view(),
        name="inventory-movement-list",
    ),
    path(
        "inventory/operations/<uuid:operation_id>",
        InventoryOperationDetailView.as_view(),
        name="inventory-operation-detail",
    ),
]
