# Generated by Django 5.2.4 on 2026-07-28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.booking_requests.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0004_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_number",
                    models.CharField(
                        default=apps.booking_requests.models.generate_booking_request_public_number,
                        editable=False,
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("WEBSITE", "Сайт"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "Нова"), ("PROCESSED", "Оброблена")],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=160,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "phone_normalized",
                    models.CharField(db_index=True, editable=False, max_length=16),
                ),
                ("contact_handle", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True, max_length=2000)),
                ("preferred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=160),
                ),
                (
                    "processed_by_display_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_booking_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at", "-id"],
                        name="booking_req_status_time_idx",
                    ),
                    models.Index(
                        fields=["source", "-created_at", "-id"],
                        name="booking_req_source_time_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("public_number", ""), _negated=True),
                        name="booking_req_public_number_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("client_name", ""), _negated=True),
                        name="booking_req_client_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("phone", ""), _negated=True),
                        name="booking_req_phone_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("phone_normalized", ""), _negated=True),
                        name="booking_req_phone_normalized_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="booking_req_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("processed_at__isnull", True),
                                ("processed_by__isnull", True),
                                ("processed_by_display_name", ""),
                                ("status", "NEW"),
                            ),
                            models.Q(
                                ("processed_at__isnull", False),
                                ("processed_by__isnull", False),
                                ("status", "PROCESSED"),
                                models.Q(
                                    ("processed_by_display_name", ""),
                                    _negated=True,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="booking_req_processing_consistent",
                    ),
                ],
            },
        ),
    ]
