# Generated by Django 5.2.16 on 2026-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_requests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingrequest",
            name="booking_req_client_name_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="bookingrequest",
            name="booking_req_phone_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="bookingrequest",
            name="booking_req_phone_normalized_not_empty",
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="service",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="client_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="phone_normalized",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=16
            ),
        ),
    ]
