# Generated by Django 5.2.16 on 2026-07-27 23:08

import uuid
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_booking_request_api_credential(apps: Any, schema_editor: Any) -> None:
    credential = apps.get_model("booking_requests", "BookingRequestApiCredential")
    credential.objects.get_or_create(pk=1)


def remove_booking_request_api_credential(apps: Any, schema_editor: Any) -> None:
    credential = apps.get_model("booking_requests", "BookingRequestApiCredential")
    credential.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking_requests",
            "0002_remove_bookingrequest_booking_req_client_name_not_empty_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequestApiCredential",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_digest", models.CharField(blank=True, editable=False, max_length=64)),
                ("token_hint", models.CharField(blank=True, editable=False, max_length=6)),
                (
                    "rotated_by_display_name",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("rotated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rotated_booking_request_api_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking request API credential",
            },
        ),
        migrations.RunPython(
            create_booking_request_api_credential,
            remove_booking_request_api_credential,
        ),
        migrations.CreateModel(
            name="BookingRequestSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission",
                        to="booking_requests.bookingrequest",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="booking_requests.bookingrequestapicredential",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="bookingrequestapicredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="booking_req_api_credential_singleton"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrequestapicredential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rotated_at__isnull", True),
                        ("rotated_by__isnull", True),
                        ("rotated_by_display_name", ""),
                        ("token_digest", ""),
                        ("token_hint", ""),
                        ("version", 0),
                    ),
                    models.Q(
                        models.Q(("token_digest", ""), _negated=True),
                        models.Q(("token_hint", ""), _negated=True),
                        ("rotated_by__isnull", False),
                        models.Q(("rotated_by_display_name", ""), _negated=True),
                        ("rotated_at__isnull", False),
                        ("version__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="booking_req_api_credential_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrequestsubmission",
            constraint=models.UniqueConstraint(
                fields=("credential", "idempotency_key"),
                name="booking_req_submission_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrequestsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                name="booking_req_submission_key_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrequestsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_hash", ""), _negated=True),
                name="booking_req_submission_hash_not_empty",
            ),
        ),
    ]
