# Generated by Django 5.2.16 on 2026-07-28 11:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_phone"),
        ("booking_requests", "0003_bookingrequestapicredential_bookingrequestsubmission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSubscription",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="telegram_subscription",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=160)),
                ("is_enabled", models.BooleanField(default=True)),
                ("linked_at", models.DateTimeField()),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("user_id",),
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "chat_id"], name="telegram_sub_enabled_chat_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("disabled_at__isnull", True), ("is_enabled", True)),
                            models.Q(("disabled_at__isnull", False), ("is_enabled", False)),
                            _connector="OR",
                        ),
                        name="telegram_sub_enabled_consistent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                ("update_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("CALLBACK_QUERY", "Callback query"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("command", models.CharField(blank=True, max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-update_id",),
                "indexes": [
                    models.Index(
                        fields=["state", "received_at"], name="telegram_update_state_time_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramLinkIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("payload_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="telegram_intent_user_time_idx"
                    ),
                    models.Index(fields=["expires_at"], name="telegram_intent_expiry_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("payload_digest", ""), _negated=True),
                        name="telegram_intent_digest_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("RETRY", "Retry"),
                            ("PERMANENT_FAILURE", "Permanent failure"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("last_synced_request_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telegram_deliveries",
                        to="booking_requests.bookingrequest",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_request_deliveries",
                        to="booking_requests.telegramsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at", "created_at"],
                        name="telegram_delivery_due_idx",
                    ),
                    models.Index(
                        fields=["booking_request", "status"], name="telegram_delivery_request_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking_request", "subscription"),
                        name="telegram_delivery_request_subscription_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)),
                        name="telegram_delivery_attempt_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_synced_request_version__gte", 0)),
                        name="telegram_delivery_synced_version_nonnegative",
                    ),
                ],
            },
        ),
    ]
