# Generated by Django 5.2.16 on 2026-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_requests", "0004_telegramsubscription_telegramupdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramupdate",
            name="callback_data",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="telegramupdate",
            name="callback_query_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="telegramupdate",
            name="chat_type",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="telegramupdate",
            name="message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
