# Generated by Django 5.2.16 on 2026-07-29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_requests", "0005_telegramupdate_callback_data_and_more"),
        ("work_items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemTelegramDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("RETRY", "Retry"),
                            ("PERMANENT_FAILURE", "Permanent failure"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("last_synced_work_item_version", models.PositiveIntegerField(default=0)),
                ("last_synced_is_overdue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_item_deliveries",
                        to="booking_requests.telegramsubscription",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telegram_deliveries",
                        to="work_items.workitem",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at", "created_at"],
                        name="work_tg_delivery_due_idx",
                    ),
                    models.Index(
                        fields=["work_item", "status"],
                        name="work_tg_delivery_item_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work_item", "subscription"),
                        name="work_tg_item_sub_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)),
                        name="work_tg_attempt_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_synced_work_item_version__gte", 0)),
                        name="work_tg_version_nonnegative",
                    ),
                ],
            },
        ),
    ]
